// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMu5KWm8p1rxhdxIaEWISfssPELKo9mas',
    appId: '1:619919144315:web:5a105cf530d34b5a1bf9de',
    messagingSenderId: '619919144315',
    projectId: 'portfolio-d4d75',
    authDomain: 'portfolio-d4d75.firebaseapp.com',
    storageBucket: 'portfolio-d4d75.appspot.com',
    measurementId: 'G-2RK4WW5LVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpnhSMjNjYnJ7d6sAea9tokHLIYby8OQw',
    appId: '1:619919144315:android:683b852054f171171bf9de',
    messagingSenderId: '619919144315',
    projectId: 'portfolio-d4d75',
    storageBucket: 'portfolio-d4d75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKO4_MfG5uMucOAyYEIaHjeoLQhP7atIQ',
    appId: '1:619919144315:ios:1d45dda38240ba121bf9de',
    messagingSenderId: '619919144315',
    projectId: 'portfolio-d4d75',
    storageBucket: 'portfolio-d4d75.appspot.com',
    iosBundleId: 'com.example.flutterPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKO4_MfG5uMucOAyYEIaHjeoLQhP7atIQ',
    appId: '1:619919144315:ios:7f5d7fd7bd1acedb1bf9de',
    messagingSenderId: '619919144315',
    projectId: 'portfolio-d4d75',
    storageBucket: 'portfolio-d4d75.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMu5KWm8p1rxhdxIaEWISfssPELKo9mas',
    appId: '1:619919144315:web:100642288516e00e1bf9de',
    messagingSenderId: '619919144315',
    projectId: 'portfolio-d4d75',
    authDomain: 'portfolio-d4d75.firebaseapp.com',
    storageBucket: 'portfolio-d4d75.appspot.com',
    measurementId: 'G-N7REN47ZT4',
  );
}
